location ~ ^/vendor/core/ {
    try_files $uri =404;
    expires 30d;
    add_header Cache-Control "public, immutable";
}

location ~ ^/themes/ {
    try_files $uri =404;
    expires 30d;
    add_header Cache-Control "public, immutable";
}
